### ISSUE TITLE
Lack of information

### ISSUE THREAD

**Issue by hasanzad** [marcus-santos/spotware_connect#2]
Hi Marcus

It is good job, I want to use it. I tried your sample code it works for me with my account information. 

But I can not find how to receive data from the broker and send some orders to the server. please advise

**Comment by marcus-santos** [comment]
Dear @hasanzad,

I encourage you to read the [usage](https://spotware-connect.readthedocs.io/en/latest/usage.html) which contains basic requests and response handling. 

Also, check [Spotware Connect API docs ](https://connect.spotware.com/docs/open_api_2) to know the types of requests and responses and their parameters avaiable for using with this client.

This is an open source project and anyone insterested in contributing with examples is welcome.

Regards.

**Comment by hasanzad** [comment]
Dear @marcus-santos 

Thanks for your feedback. I study usage and some on spotware connect api docs. in the package I could not find how to send for exampe buy order for specific asset. Please let me the brief sample code for that.


thanks in advance

**Comment by hasanzad** [comment]
Dear Marcus
Just as an example I put these sentences in your usage code and it can not handle it:
     c.emit("SubscribeSpotsReq",clientId="756_CZtaPQ2iwTOoa1tPTTpt2yyWszuiih6V80TYVPYOaOpGesYQfO"
           , symbolId = 1)  

    c.emit("AssetListReq",clientId="756_CZtaPQ2iwTOoa1tPTTpt2yyWszuiih6V80TYVPYOaOpGesYQfO")


Please advise

**Comment by lvturner** [comment]
You need some code to listen to the response that these create 

something similar to 

`@c.message(msgtype=AssetListRes)
def on_asset_list_response(msg, payload, **kwargs):
   print(payload)
`

**Comment by hasanzad** [comment]
Thanks Ivturner
still I have problem. 
I am sending the below code but with the codes to listen the response there is no output. please advise

@c.exec_events
def receive():
    c.emit("AssetListReq")

**Comment by lvturner** [comment]
In the code example you provided, it looks like you aren't making proper use of the decorator for receiving messages - perhaps paste a larger code sample?

**Comment by hasanzad** [comment]
Thanks. please find as below:

#!/usr/bin/env python
# coding: utf-8

import spotware_connect as sc
c = sc.Client()
MyID= "756_CZtaPQ2iwTOoa1tPTTpt2yyWszuiih6V80TYVPYOaOpGesYQfO"
MySecret="QRJyQI1QXdC5DQKdWzOucnrr9OV04tXEpvRjINfZIXnhl3F5X4"
@c.event  # on connect event handler
def connect():
    c.emit("VersionReq")  # send a ProtoOAVersionReq
    # send a ProtoOAVersionReq with a clientMsgId
    c.emit("VersionReq", msgid="V1")

    # send a ProtoOAApplicationAuthReq with data
    c.emit("ApplicationAuthReq", clientId=MyID,
          clientSecret=MySecret)
@c.exec_events #request for asset list
def receive():
    c.emit("AssetListReq",MyID)    
@c.event  # on disconnect event handler
def disconnect():
    print("Disconencted")
@c.event  # global message receive handler
def message(msg, payload, **kargs):  # access ProtoMessage or its payload objects
    print("Global Received message ", repr(msg))
    print("Global Received payload ", repr(payload))
@c.message(msgtype="AssetListRes") #response for Asset List
def on_asset_list_response(msg, payload,**kwargs):
    print(payload)
@c.message(msgtype="ErrorRes")  # handle ProtoOAErrorRes messages
def on_error(payload, **kargs):
    print("Error: ", repr(payload))
    c.stop()  # stops client
@c.message(msgtype="VersionRes")  # handle ProtoOAVersionRes messages
# access version atribute of ProtoOAVersionRes
def on_version(msg, payload, version, **kargs):
    print("Api Version: ", version)
@c.message(msgid="V1")  # handle messages with clientMsgId=V1
def on_version(msg, payload, **kargs):
    print("Received Message with msgid 'V1': ", repr(payload))
# handle ProtoOAApplicationAuthRes messages
@c.message(msgtype="ApplicationAuthRes")
def on_auth_ok(**kargs):
    print("Application Authorized")
    c.stop()  # stops client
c.start(timeout=5)  # optional: set a timeout interval in seconds

**Comment by lvturner** [comment]
Please tidy up the formatting on that code - it’s too difficult for me to read

**Comment by hasanzad** [comment]
It has been sent to your email. Tnx at lvturner@me.com

**Comment by lvturner** [comment]
You should first validate if the code here

```
@c.exec_events #request for asset list
def receive():
    c.emit("AssetListReq",MyID)    
```

Actually ever gets called

Further more, you stop the client when you finish authentication, so you won't receive any further messages after you have successfully authenticated.

```
# handle ProtoOAApplicationAuthRes messages
@c.message(msgtype="ApplicationAuthRes")
def on_auth_ok(**kargs):
    print("Application Authorized")
    c.stop()  # stops client
```

As an experiment, I would remove that `c.stop()` and replace it with `c.emit("AssetListReq",MyID)` instead

Furthermore - you really should be more careful with your ID and Secret Key - this provides access to your CTrader account, especially if this is linked to a live account, you really don't want strangers on the internet to be able to make API calls to your account. If it's just a demo account, then 'fine' but it's a habit one should strive to avoid regardless of the scope of the token.

**Comment by hasanzad** [comment]
Tnx for your comment:
1. regarding the ID and secret key, it is related only to demo account and I have another application which is related to real accounts, thanks for your concern.
2.  I replaced the c.emit with c.stop in that position but I face ERROR, please run yourself as well. if possible

**Comment by lvturner** [comment]
2 is not the action I suggested. You most likely don't want `c.stop()` anywhere.

I have little desire to run any untested/buggy code - it is beyond my scope as helpful internet citizen.

**Comment by hasanzad** [comment]
Thanks for your comments they were useful for me.
