### ISSUE TITLE
AccountAuthRes answer not received

### ISSUE THREAD

**Issue by Matx00** [marcus-santos/spotware_connect#4]
* spotware_connect version: 0.1.2
* Python version: 3.9
* Operating System: macOS Big Sur

### Description
Hi,
first of all thank you for this library, it could be really useful.
Said that I would like to send an Account Authorization Request but once I send it I don't receive an answer.

### What I Did

I'v tried the Usage code you provide with a simple modification of the function `connect`

```
@c.event  
def connect():   
    c.emit("ApplicationAuthReq", clientId=client_ID,
           clientSecret=client_Secret)
    c.emit("AccountAuthReq", ctidTraderAccountId=ctidTraderAccountId,
           accessToken=access_token)
```
In this way the `AccountAuthRes` answer message should be handled by
```

@c.event  # global message receive handler
def message(msg, payload, **kargs):  # access ProtoMessage or its payload objects
    print("Global Received message ", repr(msg))
    print("Global Received payload ", repr(payload))

```

but I don't receive any answer and it disconnects automatically after the timeout period. Is it normal, or is it a problem of my account/code?
I can't proceed to execute trades if I don't authorize the account.

Thank you very much

**Comment by marcus-santos** [comment]
Hi @Matx00 ,

In the code provided, you are trying to authorize the App and the Account at the same time. However, this is not possible in the Open Api 2 provided by Spotware. 

You must first submit an ApplicationAuthReq, handle its response and then submit any AccountAuthReq you wish. So, the basic authorization flow is like:

```
@c.event  # on connect event handler
def connect():
    # send a ProtoOAApplicationAuthReq to authorize the App
    c.emit("ApplicationAuthReq", clientId="YOUR_APP_CLIENT_ID",
           clientSecret="YOUR_APP_CLIENT_SECRET")

# handle ProtoOAApplicationAuthRes messages and authorize an Account
@c.message(msgtype="ApplicationAuthRes")
def on_auth_ok(**kargs):
    c.emit("AccountAuthReq", ctidTraderAccountId=ctidTraderAccountId,
           accessToken=access_token)

# handle ProtoOAAccountAuthRes
@c.message(msgtype="AccountAuthRes")
    def on_acc_auth(payload, ctid, **kargs):
        # your code for the Account authorized
```

**Comment by Matx00** [comment]
Thank youu very much!
